### ISSUE TITLE
Update `Tower Forge` -> `Batch Forge`

### ISSUE THREAD

**Issue by ewels** [seqeralabs/docs#13]
The docs [here](https://docs.seqera.io/platform/latest/compute-envs/aws-batch#tower-forge) currently refer to "Tower Forge".

However, in the Seqera Platform UI, this has been renamed "Batch Forge":

![CleanShot 2024-04-04 at 23 53 21@2x](https://github.com/seqeralabs/docs/assets/465550/04561ab9-5df8-4402-a005-25b849285b21)

**Comment by jason-seqera** [comment]
@ewels,

Looks like we use Tower Forge in:

```
195 results - 56 files
```

Is this changing everywhere? For example:

```
platform_versioned_docs/version-22.4.0/faqs.mdx:
platform_versioned_docs/version-22.4.0/compute-envs/aws-batch.mdx:
platform_versioned_docs/version-22.4.0/compute-envs/azure-batch.mdx:
...
ect.
```

Thanks!

**Comment by jason-seqera** [comment]
@llewellyn-sl @justinegeffen 

Longer term (intermediate?) we could start using JSX/MDX variable interpolation for these, so we just have this defined in one place and elsewhere we can use `{towerbatch}` or just `{batch}` or whatever and it can be defined as `batch: 'Batch Forge'` centrally, like with SP and other terms. Just a thought.

**Comment by ewels** [comment]
I wasn't aware of the name change until earlier when I asked if it would happen on slack and Maria pointed out that it already had happened 😅 So I'm not the right person to ask really.

I would _hope_ that it never gets renamed again 👀

**Comment by ewels** [comment]
Related: "Batch Forge" doesn't seem to be mentioned anywhere on the Azure docs, despite it being an option: https://docs.seqera.io/platform/latest/compute-envs/azure-batch

**Comment by llewellyn-sl** [comment]
@jason-seqera in this case, the name should just be Batch Forge everywhere, and this is not variable. So changing Tower Forge to Batch Forge in the docs is a once-off process that is not helped by the use of variables. Or am I misunderstanding your suggestion?

**Comment by llewellyn-sl** [comment]
@ewels There is a Tower Forge section describing how to create a Forge CE on the Azure Batch page https://docs.seqera.io/platform/23.4.0/compute-envs/azure-batch#tower-forge

**Comment by ewels** [comment]
Gotcha, sorry I missed it!

**Comment by jason-seqera** [comment]
@llewellyn-sl, what if it changes again? This has been known to happen, where things get rebranded that you'd never expect. Who thought Tower would rebrand? It also means the words are always correct. We'll never type Battch Forge by accident, for example. Similar to being able to do {aws} instead of Amazon Web Services (AWS) on first usage, for example. This is somewhat of an acquired taste, and we might not want to adopt this approach; but it's there for us.

**Comment by llewellyn-sl** [comment]
@jason-seqera as discussed, it will be a good idea to go ahead with variables when we can. We'll do the heavy lift of replacing these feature names manually one last time when that day comes.
